export const products = [
    {
      id: 1,
      image: "/category/download (1).jpg",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/download (1).jpg"], // 1 image
    },
    {
      id: 2,
      image: "/category/download (2).jpg",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/download (2).jpg"], // 1 image
    },
    {
      id: 3,
      image: "/category/image1.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image1.png"], // 1 image
    },
    {
      id: 4,
      image: "/category/image2.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image2.png"], // 1 image
    },
    {
      id: 5,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 6,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 7,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 8,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 9,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 10,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 11,
      image: "/category/download (2).jpg",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/download (2).jpg"], // 1 image
    },
    {
      id: 12,
      image: "/category/image1.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image1.png"], // 1 image
    },
    {
      id: 13,
      image: "/category/image2.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image2.png"], // 1 image
    },
    {
      id: 14,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 15,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 16,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 17,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 18,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 19,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
    {
      id: 20,
      image: "/category/image3.png",
      title: "Drashti Dhami Beige Embroidered Anarkali Suit Party Wear",
      originalPrice: "₹2000.00",
      discountedPrice: "₹1000.00",
      discount: "-50%",
      sales: "120 left",
      category: "Salwar Kameez",
      images: ["/category/image3.png"], // 1 image
    },
  ];
  